baseURL = 'https://xavmarch13.github.io/lattice_estimator.io/'
languageCode = 'en-us'
title = 'Lattirust estimator 0.1'
theme = ["hugo-book", "hugo-simplecite"]

[params]
    bookTheme = 'light'
    math = true

relativeURLs = true
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]